import { describe,it,expect,vi } from 'vitest';
const ledger=vi.hoisted(()=>({data:new Map<string,any>(),serial:Promise.resolve()}));
vi.mock('@google-cloud/firestore',()=>({Timestamp:{fromMillis:(ms:number)=>ms},Firestore:class{
 collection(name:string){return {doc:(id:string)=>`${name}/${id}`};}
 runTransaction(fn:any){const work=ledger.serial.then(async()=>{const writes=new Map();const result=await fn({get:async(ref:string)=>({exists:ledger.data.has(ref),data:()=>structuredClone(ledger.data.get(ref))}),set:(ref:string,v:any)=>writes.set(ref,structuredClone(v)),create:(ref:string,v:any)=>{if(ledger.data.has(ref))throw Error();writes.set(ref,structuredClone(v));}});for(const [k,v]of writes)ledger.data.set(k,v);return result;});ledger.serial=work.catch(()=>{});return work;}
}}));
import {createSiteIntake,FirestoreSiteStore,parseSiteEvent,parseSiteLead,IntakeError,type SiteStore} from './site-intake.js';
const origin='https://example.test';
const input={requestId:'ba0236d4-9f1b-41fb-bfbc-8c15f889af13',name:'Demo User',email:'demo@example.invalid',organization:'Example',useCase:'training',message:'Synthetic inquiry for validation.',consent:true as const,website:'' as const,language:'ja' as const};
const request=(path:string,body:any,extra={})=>new Request(`http://localhost${path}`,{method:'POST',headers:{origin,'content-type':'application/json',...extra},body:JSON.stringify(body)});
const memory:SiteStore={lead:vi.fn(async()=>({receipt:'AM-EXAMPLE'})),event:vi.fn(async()=>{})};
describe('private site intake',()=>{
 it('accepts portfolio inquiries without exposing a public inbox or arbitrary telemetry',async()=>{
  const app=createSiteIntake({RCAI_MARKETING_ORIGIN:origin},memory);
  for(const product of ['genie','launchloom','oathra','aisecure','agent-team']){
   const r=await app.fetch(request('/leads',{...input,useCase:product},{origin:'https://forifor.github.io'}));
   expect(r.status).toBe(201);
   expect(parseSiteEvent({event:'artifact_open',scenario:product,language:'ja'}).scenario).toBe(product);
  }
  expect((await app.fetch(new Request('http://localhost/leads',{headers:{origin:'https://forifor.github.io'}}))).status).toBe(405);
  expect((await app.fetch(request('/leads',input,{origin:'https://forifor.github.io.attacker.test'}))).status).toBe(403);
  expect(()=>parseSiteLead({...input,useCase:'private customer name'})).toThrow();
 });
 it('accepts only consented inquiries and returns a receipt after storage',async()=>{const app=createSiteIntake({RCAI_MARKETING_ORIGIN:origin},memory);const r=await app.fetch(request('/leads',input));expect(r.status).toBe(201);expect(await r.json()).toEqual({receipt:'AM-EXAMPLE'});expect((await app.fetch(request('/leads',{...input,consent:false}))).status).toBe(400);expect((await app.fetch(request('/leads',{...input,website:'spam'}))).status).toBe(400);});
 it('blocks foreign origins, reading records, oversized bodies and unknown fields',async()=>{const app=createSiteIntake({RCAI_MARKETING_ORIGIN:origin},memory);expect((await app.fetch(request('/leads',input,{origin:'https://foreign.test'}))).status).toBe(403);expect((await app.fetch(new Request('http://localhost/leads',{headers:{origin}}))).status).toBe(405);expect((await app.fetch(request('/leads',{...input,message:'x'.repeat(9000)},{'content-length':'1'}))).status).toBe(413);expect((await app.fetch(request('/leads',{...input,recording:'private'}))).status).toBe(400);});
 it('never reports successful receipt when persistence fails',async()=>{const app=createSiteIntake({RCAI_MARKETING_ORIGIN:origin},{...memory,lead:async()=>{throw Error('storage unavailable');}});const r=await app.fetch(request('/leads',input));expect(r.status).toBe(503);expect(await r.json()).toEqual({error:'UNAVAILABLE'});});
 it('limits analytics to enum values, excluding content and fake lead counts',async()=>{expect(()=>parseSiteEvent({event:'demo_start',scenario:'tasks',language:'ja',email:'secret'})).toThrow();expect(()=>parseSiteEvent({event:'lead_submit',scenario:'tasks',language:'ja'})).toThrow();expect(parseSiteEvent({event:'vrm_preview_open',scenario:'tasks',language:'ja'}).event).toBe('vrm_preview_open');expect(()=>parseSiteEvent({event:'demo_start',scenario:'arbitrary secret',language:'ja'})).toThrow();const app=createSiteIntake({RCAI_MARKETING_ORIGIN:origin},memory);expect((await app.fetch(request('/events',{event:'demo_complete',scenario:'tasks',language:'ja'}))).status).toBe(204);});
 it('retries idempotently across store instances and rejects a changed payload',async()=>{ledger.data.clear();const a=new FirestoreSiteStore('test','test',()=>0),b=new FirestoreSiteStore('test','test',()=>0);const one=await a.lead(parseSiteLead({...input}));expect(await b.lead(parseSiteLead({...input}))).toEqual(one);expect(ledger.data.get('ai_meeting_site_lead_usage/1970-01-01').total).toBe(1);await expect(b.lead(parseSiteLead({...input,message:'A different inquiry body'}))).rejects.toMatchObject({status:409});const stored=ledger.data.get(`ai_meeting_site_leads/${input.requestId}`);expect(stored.expiresAt).toBe(90*86400000);expect(stored).not.toHaveProperty('website');});
 it('serializes concurrent daily quota reservations and fails closed on corruption',async()=>{ledger.data.clear();const a=new FirestoreSiteStore('test','test',()=>0);const make=(n:number)=>parseSiteLead({...input,requestId:`ba0236d4-9f1b-41fb-bfbc-8c15f889af1${n}`});const results=await Promise.allSettled([1,2,3,4].map(n=>a.lead(make(n))));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(3);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);ledger.data.set('ai_meeting_site_lead_usage/1970-01-01',{total:'bad',emails:{}});await expect(a.lead(make(5))).rejects.toBeInstanceOf(IntakeError);});
 it('stores only daily aggregate event counts and preserves the cap',async()=>{ledger.data.clear();const a=new FirestoreSiteStore('test','test',()=>0);const event=parseSiteEvent({event:'github_outbound',scenario:'tasks',language:'ja'});await a.event(event);const row=ledger.data.get('ai_meeting_site_events/1970-01-01');expect(row).toEqual({total:1,counts:{'github_outbound:tasks:ja':1},expiresAt:90*86400000});ledger.data.set('ai_meeting_site_events/1970-01-01',{...row,total:20000});await expect(a.event(event)).rejects.toMatchObject({status:429});});
});
